### ISSUE TITLE
Travis CI / Sonar Cloud 적용 요청

### ISSUE THREAD

**Issue by Pinepond** [eGovFramework/egovframe-runtime#58]
안녕하세요~!

Github 에서도 Build 상황이나, 정적코드분석 결과 , Test Coverage 를 쉽게 볼 수 있도록,
Travis CI / Sonar Cloud 적용 요청 드립니다.

\- 작업 순서 
1. [Travis CI](https://travis-ci.com/) 가입 후 , travis 의 가이드에 따라 repository 등록합니다.
2. [Sonar Cloud](https://sonarcloud.io/) 가입 후 , sonar 의 가이드에 따라 repository 등록합니다.
3. 프로젝트의 root 경로에 .travis.yml 추가, yml 파일의 내용은 아래와 같습니다.
```yml
language: java
jdk:
  - openjdk8

branches:
  only:
    - ci-setting

# Travis CI 서버의 Home
cache:
  directories:
    - $HOME/.m2

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - *****@gmail.com #Travis 수행결과를 수신할 메일을 지정합니다.

addons:
  sonarcloud:
    organization: "eGovFramework" #Gihub Organization 정보를 입력합니다. 
    token:
      secure: "***********" #Sonar 의 가이드에 따라 travis 용 token 을 jem 을 통해 암호화 후 적용해야합니다.

# jdk 환경에서 build 후, jdk11 설치하여 sonar 를 수행 합니다. (jdk8 에서는 sonar cloud 사용 불가)
# sonar 를 통해 정적코드분석을 수행하고,
# jacoco 를 통해 test coverage report 를 생성하여 sonar 로 업로드 합니다.
# pom.xml 에서 test 를 skip 한경우 jacoco report 가 새성되지 않습니다.
script:
  - mvn -B clean org.jacoco:jacoco-maven-plugin:prepare-agent install org.jacoco:jacoco-maven-plugin:report
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
  - chmod +x $TRAVIS_BUILD_DIR/install-jdk.sh
  - export JAVA_HOME=$HOME/openjdk11
  - $TRAVIS_BUILD_DIR/install-jdk.sh -F 11 --target $JAVA_HOME
  - find ./ -name "%jacoco%"
# -Dsonar.projectKey 값은 Sonar Cloud 에 생성된 정보에 맞춰 수정해야합니다.
  - mvn -B sonar:sonar -DskipTests -Dsonar.projectKey=****  -Dsonar.coverage.jacoco.xmlReportPaths=$(find "$(pwd)" -path '*jacoco.xml' | sed 's/.*/&/' | tr '\n' ',')


```
